Added required notebook
databrickslabs/discoverx pull request #97
Opened 2024-01-02 14:06 UTC by souravg-db

2024-01-05 15:17 UTC, edurdevic requested changes
We are updating the owner twice now.
Please remove one of the two triggers

2024-01-05 15:17 UTC, edurdevic commented on examples/update_owner_of_data_objects.py
> +(dx.from_tables(from_table_statement)
I think we don't need this one.

2024-01-05 16:45 UTC, souravg-db commented on examples/update_owner_of_data_objects.py
> +(dx.from_tables(from_table_statement)
Removed

2024-01-08 20:17 UTC, edurdevic approved these changes
LGTM

2024-01-08 20:17 UTC, merged